#config_version=6

sound_system:
  buffer: 2048
  channels: 1
  enabled: True
  frequency: 44100
  #master_volume: 0.8
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: .6
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.85
    sfx:
      type: standard
      simultaneous_sounds: 8
      volume: 0.8

sounds:
  beep:
    file: beep-01a.wav